version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-event-db
    restart: always
    environment:
      MYSQL_DATABASE: eventdb
      MYSQL_USER: eventuser
      MYSQL_PASSWORD: eventpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
